import Head from 'next/head';
import { signIn, signOut, useSession } from 'next-auth/client';
import TracksList from '../components/TracksList';

export default function Home() {
  const [session, loading] = useSession();

  if (loading) return <p>Loading...</p>;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {!session && (
          <>
            Not signed in <br />
            <button onClick={() => signIn('spotify')}>Sign in</button>
          </>
        )}
        {session && (
          <>
            Signed in as {session.user?.name} <br />
            <button onClick={() => signOut('spotify')}>Sign out</button>
            <TracksList />
          </>
        )}
      </main>
    </div>
  );
}
